#!/bin/bash

cat inputs/day07 \
	| cargo run --release --bin day07 \
	> inputs/day07.pl

swipl \
	--quiet \
	-f inputs/day07.pl \
	-g 'findall(X, contents(X, shiny_gold), Solutions), length(Solutions, Len), writef("Part One: %t", [Len]), nl.' \
	-g 'size([shiny_gold], Z), writef("Part Two: %t", [Z]), nl.' \
	-t 'true.'
