[package]
name = "d2022"
publish = false
version = "0.1.0"
edition = "2021"
rust-version = "1.74"

[lints]
workspace = true

[dependencies]
daocutil = { path = "../daocutil" }
anyhow = "1.0.81"
thiserror = "2.0.3"
itertools = "0.14.0"
nu-ansi-term = "0.50.0"
regex = "1.10.4"
